# Generated by Django 6.0.3 on 2026-07-15 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='chat.room'),
        ),
        migrations.AddField(
            model_name='chatuser',
            name='pending_cleanup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatuser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_index=True, max_length=4, unique=True),
        ),
    ]
